#!/bin/bash

PROG_PATH="/home/challenge/ro"
PROG_NAME="badtable"
PATCH_NAME="badtable-patched"

# Retrieves the binary from the containers and substitutes it with a patched one
# Check if a container name is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <container-name>"
    exit 1
fi
if [ ! -f "./scripts/patch.py" ]; then
    echo "File ./scripts/patch.py does not exist"
    exit
fi

echo "Getting ${PROG_PATH} from container $1"
docker cp $1:${PROG_PATH}/${PROG_NAME} .

python3 ./scripts/patch.py ${PROG_NAME} ${PATCH_NAME}

chmod +x ${PATCH_NAME}
docker cp ${PATCH_NAME} $1:${PROG_PATH}/${PROG_NAME}

rm -f ${PROG_NAME} ${PATCH_NAME}